version: '3'

volumes:
  postgres_data:

services:
  rabbit:
    image: rabbitmq:3.8.8-management-alpine
    container_name: rabbit
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
